### ISSUE TITLE
Unable to hit breakpoint in NL2EFSkill.cs class

### ISSUE THREAD

**Issue by saisescapades** [anthonypuppo/sk-nl2ef-plugin#2]
This is a fantastic piece of code demonstrating Text2Sql using Sematic Kernel. I cloned it locally to give it a try and while the api works great, I wasn't able to get the breakpoint that I set in NL2EFSkill.cs to hit.

![image](https://github.com/anthonypuppo/sk-nl2ef-plugin/assets/50072973/fc3abf7a-f338-4dba-8bad-95ac2fc37728)

**Comment by anthonypuppo** [comment]
How are you debugging? If you start the process through the Visual Studio debugger it should attach properly. I would verify you're attaching to the correct process and, if that isn't it, cleaning any outdated files by manually deleting the `bin` and `obj` folders.

**Comment by anthonypuppo** [comment]
Closing, if you're still having trouble please create another issue!
